export const agencies = [
  {
    id: "sl-mocti",
    name: "Sierra Leone MoCTI / DSTI",
    country: "sierra-leone",
    roles: ["exchange-operator", "digital-governance"],
  },
  {
    id: "sl-nppa",
    name: "Sierra Leone NPPA",
    country: "sierra-leone",
    roles: ["procurement-owner"],
  },
  {
    id: "sl-mof",
    name: "Sierra Leone Ministry of Finance",
    country: "sierra-leone",
    roles: ["treasury-owner"],
  },
  {
    id: "eth-mesob",
    name: "Ethiopia MESOB",
    country: "ethiopia",
    roles: ["service-orchestrator"],
  },
  {
    id: "eth-fayda",
    name: "Ethiopia Fayda Digital ID",
    country: "ethiopia",
    roles: ["identity-provider"],
  },
  {
    id: "zm-smart-zambia",
    name: "Smart Zambia Institute",
    country: "zambia",
    roles: ["exchange-operator", "digital-governance"],
  },
  {
    id: "zm-zilas",
    name: "ZILAS land administration",
    country: "zambia",
    roles: ["land-registry-owner"],
  },
  {
    id: "zm-forestry",
    name: "Zambia forestry and natural-resource agencies",
    country: "zambia",
    roles: ["forest-registry-owner"],
  },
];

export const services = [
  {
    id: "sl-procurement-payment-status",
    country: "sierra-leone",
    ownerAgencyId: "sl-mof",
    layer: "Data exchange",
    purpose: "procurement-to-payment",
    description: "Return supplier payment status for an awarded contract.",
    allowedRequesterRoles: ["procurement-owner", "exchange-operator"],
    requiredFields: ["supplierId", "contractId"],
    responseFields: ["paymentStatus", "treasuryApproval", "settlementReference"],
  },
  {
    id: "sl-supplier-contract-check",
    country: "sierra-leone",
    ownerAgencyId: "sl-nppa",
    layer: "Operations",
    purpose: "procurement-to-payment",
    description: "Validate supplier and contract award status.",
    allowedRequesterRoles: ["treasury-owner", "exchange-operator"],
    requiredFields: ["supplierId", "contractId"],
    responseFields: ["supplierStatus", "contractStatus", "awardDate"],
  },
  {
    id: "eth-identity-assertion",
    country: "ethiopia",
    ownerAgencyId: "eth-fayda",
    layer: "Identity",
    purpose: "one-stop-services",
    description: "Return a minimal identity assertion for a public service journey.",
    allowedRequesterRoles: ["service-orchestrator"],
    requiredFields: ["personToken", "serviceId"],
    responseFields: ["identityVerified", "assuranceLevel", "exceptionRequired"],
  },
  {
    id: "zm-land-parcel-check",
    country: "zambia",
    ownerAgencyId: "zm-zilas",
    layer: "Registries",
    purpose: "climate-land",
    description: "Return a minimal parcel status for a land or climate-service workflow.",
    allowedRequesterRoles: ["exchange-operator", "forest-registry-owner"],
    requiredFields: ["parcelId", "requestPurpose"],
    responseFields: ["parcelStatus", "tenureType", "lastUpdated"],
  },
  {
    id: "zm-forest-permit-check",
    country: "zambia",
    ownerAgencyId: "zm-forestry",
    layer: "Registries",
    purpose: "climate-land",
    description: "Return timber or forest permit validity without exposing unrelated records.",
    allowedRequesterRoles: ["exchange-operator", "land-registry-owner"],
    requiredFields: ["permitId", "requestPurpose"],
    responseFields: ["permitStatus", "provenanceStatus", "expiryDate"],
  },
];

export const sampleResponses = {
  "sl-procurement-payment-status": {
    paymentStatus: "queued-for-settlement",
    treasuryApproval: "approved",
    settlementReference: "T24-REF-2026-0004",
    internalBudgetLine: "redacted-by-policy",
  },
  "sl-supplier-contract-check": {
    supplierStatus: "verified",
    contractStatus: "awarded",
    awardDate: "2026-03-14",
    evaluationNotes: "redacted-by-policy",
  },
  "eth-identity-assertion": {
    identityVerified: true,
    assuranceLevel: "medium",
    exceptionRequired: false,
    rawBiometricRecord: "redacted-by-policy",
  },
  "zm-land-parcel-check": {
    parcelStatus: "active",
    tenureType: "customary",
    lastUpdated: "2026-02-02",
    ownerName: "redacted-by-policy",
  },
  "zm-forest-permit-check": {
    permitStatus: "valid",
    provenanceStatus: "traceable",
    expiryDate: "2026-12-31",
    commercialVolume: "redacted-by-policy",
  },
};
